// English content — edit freely. Keep keys in sync with ka.mjs.
export default {
  lang: 'en',
  dir: 'ltr',
  path: '/',
  altPath: '/ka/',
  altLabel: 'ქართ',
  altTitle: 'ქართულად',
  selfLabel: 'EN',
  meta: {
    title: 'Giorgi Samsiani — Full-Stack Web Developer · WordPress, WooCommerce, Next.js',
    description:
      'Full-stack web developer in Tbilisi, Georgia. Custom and headless WordPress, WooCommerce engineering, Next.js and TypeScript front ends, bank and ERP integrations, performance and technical SEO.',
    ogLocale: 'en_US',
  },
  ui: {
    skip: 'Skip to content',
    nav: 'Sections',
    theme: 'Toggle colour theme',
    print: 'Save as PDF',
    printShort: 'PDF',
    language: 'Language',
    copy: 'copy',
    copied: 'copied',
    legend: 'Depth of use',
    levels: { core: 'Core', strong: 'Strong', working: 'Working' },
    levelHints: { core: 'daily, production', strong: 'regular', working: 'as needed' },
    updated: 'Last updated',
    builtWith: 'Plain HTML & CSS · no trackers',
    top: 'Back to top',
    atAGlance: 'At a glance',
  },
  hero: {
    eyebrow: 'Curriculum vitae · 2026',
    name: 'Giorgi Samsiani',
    role: 'Full-Stack Web Developer',
    subrole: 'WordPress · WooCommerce · Next.js · TypeScript',
    tagline: 'I build websites and e-commerce systems that stay fast, talk to banks and ERPs, and hold up under real traffic.',
    location: 'Tbilisi, Georgia',
    availability: 'Open to remote and contract work',
    facts: [
      { value: '10+', label: 'years building for the web' },
      { value: 'PHP · TS', label: 'primary languages' },
      { value: 'WP · Next', label: 'primary platforms' },
      { value: 'KA · EN', label: 'product locales shipped' },
    ],
  },
  contact: {
    heading: 'Contact',
    items: [
      { label: 'Email', value: 'contact@samsiani.com', href: 'mailto:contact@samsiani.com', copy: true },
      { label: 'Phone', value: '+995 599 62 03 03', href: 'tel:+995599620303', copy: true },
      { label: 'GitHub', value: 'github.com/Samsiani', href: 'https://github.com/Samsiani' },
      { label: 'Web', value: 'samsiani.com', href: 'https://samsiani.com' },
    ],
  },
  sections: {
    profile: {
      id: 'profile',
      title: 'Profile',
      paragraphs: [
        'I am a full-stack developer who has spent more than a decade shipping commercial websites and e-commerce systems for Georgian and international businesses. WordPress and WooCommerce are my home platform: custom themes and plugins, stores built on Divi, Avada, Elementor or WoodMart, and headless builds where WordPress is the content and commerce API behind a Next.js front end.',
        'My work sits where the storefront meets the back office: banks, ERPs, delivery and SMS providers behind the shop. I own the whole path from a Figma file to a deployed, monitored server, and I care most about the unglamorous parts: data integrity, performance under load, and releases that do not break. I also design and sell my own line of WordPress and WooCommerce plugins, so I write code that other developers install, update and depend on.',
      ],
    },
    skills: {
      id: 'skills',
      title: 'Stack & skills',
      lead: 'Grouped by where they sit in a system. Depth reflects how the tool is actually used in production work, not a self-rating.',
      groups: [
        {
          title: 'WordPress & WooCommerce',
          lead: 'Custom builds, headless setups and stores that stay maintainable.',
          items: [
            { name: 'Custom WordPress development · themes, child themes, CPTs, ACF', level: 'core' },
            { name: 'WooCommerce customisation · checkout, product types, pricing, roles', level: 'core' },
            { name: 'Headless WordPress · REST, WPGraphQL, Store API behind Next.js', level: 'core' },
            { name: 'Plugin architecture · hooks, REST, cron, WP-CLI, auto-updates', level: 'core' },
            { name: 'Page builders · Divi, Avada, Elementor, WPBakery, Gutenberg / FSE', level: 'core' },
            { name: 'Premium themes · WoodMart, Flatsome, Astra, Kadence', level: 'strong' },
            { name: 'Multilingual · WPML, Polylang, TranslatePress, custom engine', level: 'core' },
            { name: 'Performance · LiteSpeed Cache, Redis object cache, WP Rocket', level: 'strong' },
            { name: 'Security & hardening · WAF, malware cleanup, backups, updates', level: 'strong' },
            { name: 'Migrations & maintenance · hosting moves, PHP upgrades, staging', level: 'strong' },
          ],
        },
        {
          title: 'Front end & UI',
          lead: 'Typed, accessible interfaces built from design files.',
          items: [
            { name: 'TypeScript', level: 'core' },
            { name: 'React 19', level: 'core' },
            { name: 'Next.js 16 · App Router, server actions', level: 'core' },
            { name: 'Vue 3 + Vite', level: 'strong' },
            { name: 'Tailwind CSS', level: 'strong' },
            { name: 'Modern CSS · container queries, view transitions, oklch', level: 'strong' },
            { name: 'Figma → production', level: 'strong' },
            { name: 'Accessibility · WCAG 2.1 AA', level: 'strong' },
            { name: 'Design systems · tokens, components, dark mode', level: 'strong' },
            { name: 'Expo / React Native', level: 'working' },
          ],
        },
        {
          title: 'Back end & data',
          lead: 'Server code that stays correct when the store is busy.',
          items: [
            { name: 'PHP 8', level: 'core' },
            { name: 'WooCommerce internals · gateways, shipping, Store API, HPOS', level: 'core' },
            { name: 'MySQL / MariaDB', level: 'core' },
            { name: 'REST & GraphQL API design', level: 'core' },
            { name: 'Laravel 12', level: 'strong' },
            { name: 'Node.js + Hono', level: 'strong' },
            { name: 'SQLite', level: 'strong' },
            { name: 'Redis & object caching', level: 'strong' },
            { name: 'Queues, cron & background jobs', level: 'strong' },
            { name: 'Python / Django', level: 'working' },
          ],
        },
        {
          title: 'Payments & integrations',
          lead: 'The part of the stack most people avoid.',
          items: [
            { name: 'Georgian bank gateways · BOG, TBC, Liberty, Credo, Flitt, iPay', level: 'core' },
            { name: 'Installment & BNPL flows', level: 'core' },
            { name: 'ERP synchronisation · 1C, Fina, Balance', level: 'core' },
            { name: 'Webhooks, polling & reconciliation', level: 'core' },
            { name: 'Apple Pay via bank processors', level: 'strong' },
            { name: 'Delivery & logistics APIs', level: 'strong' },
            { name: 'SMS gateways', level: 'strong' },
            { name: 'OAuth 2 / SSO / JWT', level: 'strong' },
          ],
        },
        {
          title: 'Infrastructure & delivery',
          lead: 'From a bare VPS to a monitored, cached, auto-deployed site.',
          items: [
            { name: 'Linux VPS administration', level: 'core' },
            { name: 'OpenLiteSpeed / CyberPanel', level: 'core' },
            { name: 'GitHub Actions CI/CD', level: 'core' },
            { name: 'Cloudflare · DNS, cache rules, WAF, bot control', level: 'core' },
            { name: 'cPanel / DirectAdmin', level: 'strong' },
            { name: 'nginx / Apache / php-fpm', level: 'strong' },
            { name: 'PM2 & Node process management', level: 'strong' },
            { name: 'TLS / ACME, LiteSpeed Cache', level: 'strong' },
            { name: 'Mail · Postfix, Dovecot, Exim, DMARC', level: 'working' },
            { name: 'Docker', level: 'working' },
          ],
        },
        {
          title: 'SEO, performance & analytics',
          lead: 'Sites that are found, and fast when they are.',
          items: [
            { name: 'Technical SEO', level: 'core' },
            { name: 'Core Web Vitals & LCP tuning', level: 'strong' },
            { name: 'Structured data · JSON-LD', level: 'strong' },
            { name: 'i18n & hreflang', level: 'strong' },
            { name: 'Crawl budget & faceted-navigation control', level: 'strong' },
            { name: 'Google Search Console & crawl diagnostics', level: 'strong' },
            { name: 'GA4 · Tag Manager · Looker Studio', level: 'strong' },
            { name: 'Rank Math / Yoast', level: 'strong' },
          ],
        },
        {
          title: 'Engineering practice & AI tooling',
          lead: 'How the code gets written, checked and released.',
          items: [
            { name: 'Git · trunk-based, semantic releases', level: 'core' },
            { name: 'Claude Code & agentic workflows', level: 'core' },
            { name: 'Multilingual products · WPML, Polylang & custom engines', level: 'core' },
            { name: 'Vitest · PHPUnit · test-gated CI', level: 'strong' },
            { name: 'MCP servers & tool integration', level: 'strong' },
            { name: 'Technical writing · specs, runbooks, changelogs', level: 'strong' },
          ],
        },
      ],
    },
    abilities: {
      id: 'abilities',
      title: 'What I can own end to end',
      lead: 'Outcomes I deliver alone, from first call to production.',
      items: [
        { title: 'Figma to production', text: 'Turn a design file into a typed, accessible Next.js or Vue front end with a real build pipeline, not a static mock-up.' },
        { title: 'Custom WordPress builds', text: 'Design and build WordPress sites the way the business works: custom post types, ACF models, editor-friendly blocks, and a theme that stays fast after the tenth plugin.' },
        { title: 'Headless WordPress', text: 'Keep WordPress as the editors’ CMS and the commerce API (REST, WPGraphQL, Store API) and ship a Next.js front end that loads in under a second.' },
        { title: 'Undocumented APIs', text: 'Reverse-engineer and stabilise bank, ERP and logistics APIs with partial or outdated documentation. Probe, log every body, reconcile by polling.' },
        { title: 'Plugins others depend on', text: 'Ship WordPress and WooCommerce plugins with licensing, auto-updates, opcache-safe activators, migrations and clean uninstallers.' },
        { title: 'Store rescue', text: 'Take over a slow, hacked or half-finished WooCommerce site: audit, clean, harden, upgrade PHP and plugins, and bring it back to green Web Vitals.' },
        { title: 'Production diagnostics', text: 'Read access logs, slow logs and CPU steal to tell "your change" from "host throttle", then fix the real cause instead of restarting things.' },
        { title: 'Sync engines', text: 'Design one-way and two-way sync between shops and ERPs with idempotent upserts, plausibility guards, dry-run modes and pause switches.' },
        { title: 'Multilingual by default', text: 'Build Georgian and English products where every cache key, URL and template is language-aware from day one.' },
      ],
    },
    workstyle: {
      id: 'work-style',
      title: 'How I work',
      lead: 'Habits that hold up on client sites at 2 a.m.',
      items: [
        { title: 'Check the code before blaming the cache.', text: 'Every bug is reproduced and traced to a line before it gets a fix. "Probably caching" is not a diagnosis.' },
        { title: 'Small, verified steps.', text: 'Build in thin slices, verify the user-visible result once, move on. No blind rewrites, no untested "should work".' },
        { title: 'Read-only until told otherwise.', text: 'Production data, client stores and third-party systems are treated as read-only unless the task explicitly changes them.' },
        { title: 'Plan, then build, then review.', text: 'Complex work starts as a written spec with a review gate. It is built in slices, tested, and released through CI.' },
        { title: 'Logs that answer questions.', text: 'Every payment, sync or gateway call records its full request and response, so tomorrow’s incident is a lookup, not a guess.' },
        { title: 'Async and written.', text: 'Clear commits, changelogs and runbooks so the next person, or the next AI agent, can pick up exactly where I stopped.' },
      ],
    },
    principles: {
      id: 'principles',
      title: 'Principles',
      lead: 'Rules I have paid for, in production.',
      items: [
        { title: 'Performance is a constraint, not a feature.', text: 'Per-request database overhead on a hot path is a bug, and it is treated like one.' },
        { title: 'Data integrity beats convenience.', text: 'A sync that could prune half a cache after a truncated fetch needs a plausibility guard before it needs a settings page.' },
        { title: 'Production changes go through CI.', text: 'Deploys happen from a pushed commit, never from a hand-copied file. Rollback is a revert.' },
        { title: 'The system of record is explicit, and it wins.', text: 'One-way syncs stay one-way. When two systems disagree, the source of truth is decided in the design, not in the incident.' },
        { title: 'Every integration is observable.', text: 'Request bodies, statuses and IDs are logged. Local state mirrors the provider’s state within one cycle.' },
        { title: 'Boring wins.', text: 'Standard tools, explicit configuration, fewer moving parts. Clever code is a liability someone else pays for.' },
      ],
    },
    experience: {
      id: 'experience',
      title: 'Experience',
      items: [
        {
          period: '2018 — present',
          role: 'Founder & Lead Developer',
          org: 'Samsiani Web',
          orgHref: 'https://samsiani.com',
          text: 'Independent studio delivering web development, technical SEO and hosting for Georgian businesses across retail e-commerce, industrial B2B, consumer lending, automotive and education. WordPress and WooCommerce builds on Divi, Avada, Elementor and WoodMart, custom plugins, and headless Next.js front ends. Long-term technical partner for several of the country’s larger online stores: storefronts, bank payments, ERP sync, performance and infrastructure.',
        },
        {
          period: '2025 — present',
          role: 'Founder, plugin products',
          org: 'CodeOn',
          orgHref: 'https://codeon.ge',
          text: 'Designs and sells a line of WordPress and WooCommerce plugins for the Georgian market: card and installment gateways for every major bank, ERP synchronisation, delivery, SMS and a multilingual engine. Licensing, auto-updates, documentation and support included.',
        },
        {
          period: 'Earlier',
          role: 'Web Developer & Project Manager',
          org: 'E-commerce brands',
          text: 'Built and managed online stores and corporate sites for wine, fashion, furniture and retail brands: development, optimisation, technical support and on-page / off-page SEO.',
        },
      ],
    },
    education: {
      id: 'languages',
      title: 'Languages',
      langsTitle: 'Languages',
      langs: [
        { name: 'Georgian', level: 'Native' },
        { name: 'English', level: 'Professional working' },
      ],
    },
    contact: {
      id: 'contact',
      title: 'Let’s talk',
      lead: 'Available for remote and contract engagements. The fastest way to reach me is email.',
      cta: 'Write to me',
    },
  },
};
