// English content — edit freely. Keep keys in sync with ka.mjs.
export default {
  lang: 'en',
  dir: 'ltr',
  path: '/',
  altPath: '/ka/',
  altLabel: 'ქართ',
  altTitle: 'ქართულად',
  selfLabel: 'EN',
  meta: {
    title: 'Giorgi Samsiani — Full-Stack Web Developer · WordPress, WooCommerce, Next.js',
    description:
      'Full-stack web developer in Tbilisi, Georgia. Custom and headless WordPress, WooCommerce engineering, Next.js and TypeScript front ends, bank and ERP integrations, performance and technical SEO.',
    ogLocale: 'en_US',
  },
  ui: {
    skip: 'Skip to content',
    nav: 'Sections',
    theme: 'Toggle colour theme',
    print: 'Save as PDF',
    printShort: 'PDF',
    language: 'Language',
    copy: 'copy',
    copied: 'copied',
    legend: 'Depth of use',
    levels: { core: 'Core', strong: 'Strong', working: 'Working' },
    levelHints: { core: 'daily, production', strong: 'regular', working: 'as needed' },
    updated: 'Last updated',
    builtWith: 'Plain HTML & CSS · no trackers',
    top: 'Back to top',
    atAGlance: 'At a glance',
  },
  hero: {
    eyebrow: 'Curriculum vitae · 2026',
    name: 'Giorgi Samsiani',
    role: 'Full-Stack Web Developer',
    subrole: 'Web applications · online stores · system integrations',
    tagline: 'I build websites and online stores that load fast, connect to banks and ERP systems, and stay reliable under load.',
    location: 'Tbilisi, Georgia',
    availability: 'Open to remote and contract work',
    facts: [
      { value: '10+', label: 'years of experience' },
      { value: 'PHP · TS', label: 'main languages' },
      { value: 'WP · Next', label: 'main platforms' },
      { value: 'KA · EN', label: 'interface languages' },
    ],
  },
  contact: {
    heading: 'Contact',
    items: [
      { label: 'Email', value: 'contact@samsiani.com', href: 'mailto:contact@samsiani.com', icon: 'mail', copy: true },
      { label: 'Phone', value: '+995 599 62 03 03', href: 'tel:+995599620303', icon: 'phone', copy: true },
      { label: 'GitHub', value: 'github.com/Samsiani', href: 'https://github.com/Samsiani', icon: 'github' },
      { label: 'Web', value: 'samsiani.com', href: 'https://samsiani.com', icon: 'globe' },
    ],
  },
  sections: {
    profile: {
      id: 'profile',
      title: 'Profile',
      paragraphs: [
        'I am a full-stack web developer based in Tbilisi. For more than ten years I have built and maintained commercial websites, online stores and internal business tools for companies in Georgia and abroad. I work alone on most projects, from the first call to the running server.',
        'On the front end I use Next.js, React, Vue and TypeScript; on the back end PHP, Laravel, Node.js and WordPress. I write custom themes and plugins, set up and repair WooCommerce stores, and run headless architectures where the CMS only serves data to a separate interface. I also make mobile apps with React Native, admin dashboards and internal CRM tools, and I manage the Linux servers, deployment and caching behind them.',
        'A large part of my work is integration. I connect shops to Georgian bank payment and installment systems, to ERP and accounting software, and to delivery, SMS and CRM providers. I design the sync engines that keep products, stock, prices and orders correct on both sides.',
        'I also develop and sell my own line of WordPress and WooCommerce plugins, so I write code that other developers install, update and depend on. Performance, security and technical SEO are part of every project, not an afterthought.',
      ],
    },
    skills: {
      id: 'skills',
      title: 'Stack & skills',
      lead: 'Grouped by where each tool sits in a system. The level shows how much I use it in production, not how well I think I know it.',
      groups: [
        {
          title: 'WordPress & WooCommerce',
          lead: 'Custom themes and plugins, online stores and headless setups.',
          items: [
            { name: 'Custom WordPress development · themes, child themes, CPTs, ACF', level: 'core' },
            { name: 'WooCommerce customisation · checkout, product types, pricing, roles', level: 'core' },
            { name: 'Headless WordPress · REST, WPGraphQL, Store API behind Next.js', level: 'core' },
            { name: 'Plugin architecture · hooks, REST, cron, WP-CLI, auto-updates', level: 'core' },
            { name: 'Page builders · Divi, Avada, Elementor, WPBakery, Gutenberg / FSE', level: 'core' },
            { name: 'Premium themes · WoodMart, Flatsome, Astra, Kadence', level: 'strong' },
            { name: 'Multilingual · WPML, Polylang, TranslatePress, custom engine', level: 'core' },
            { name: 'Performance · LiteSpeed Cache, Redis object cache, WP Rocket', level: 'strong' },
            { name: 'Security & hardening · WAF, malware cleanup, backups, updates', level: 'strong' },
            { name: 'Migrations & maintenance · hosting moves, PHP upgrades, staging', level: 'strong' },
          ],
        },
        {
          title: 'Front end & UI',
          lead: 'Typed, accessible interfaces built from design files.',
          items: [
            { name: 'TypeScript', level: 'core' },
            { name: 'React 19', level: 'core' },
            { name: 'Next.js 16 · App Router, server actions', level: 'core' },
            { name: 'Vue 3 + Vite', level: 'strong' },
            { name: 'Tailwind CSS', level: 'strong' },
            { name: 'Modern CSS · container queries, view transitions, oklch', level: 'strong' },
            { name: 'Figma → production', level: 'strong' },
            { name: 'Accessibility · WCAG 2.1 AA', level: 'strong' },
            { name: 'Design systems · tokens, components, dark mode', level: 'strong' },
            { name: 'Expo / React Native', level: 'working' },
          ],
        },
        {
          title: 'Back end & data',
          lead: 'Server code, databases and APIs.',
          items: [
            { name: 'PHP 8', level: 'core' },
            { name: 'WooCommerce internals · gateways, shipping, Store API, HPOS', level: 'core' },
            { name: 'MySQL / MariaDB', level: 'core' },
            { name: 'REST & GraphQL API design', level: 'core' },
            { name: 'Laravel 12', level: 'strong' },
            { name: 'Node.js + Hono', level: 'strong' },
            { name: 'SQLite', level: 'strong' },
            { name: 'Redis & object caching', level: 'strong' },
            { name: 'Queues, cron & background jobs', level: 'strong' },
            { name: 'Python / Django', level: 'working' },
          ],
        },
        {
          title: 'Payments & integrations',
          lead: 'Connecting shops to banks, ERP systems and service providers.',
          items: [
            { name: 'Georgian bank gateways · BOG, TBC, Liberty, Credo, Flitt, iPay', level: 'core' },
            { name: 'Installment & BNPL flows', level: 'core' },
            { name: 'ERP synchronisation · 1C, Fina, Balance', level: 'core' },
            { name: 'Webhooks, polling & reconciliation', level: 'core' },
            { name: 'Apple Pay via bank processors', level: 'strong' },
            { name: 'Delivery & logistics APIs', level: 'strong' },
            { name: 'SMS gateways', level: 'strong' },
            { name: 'OAuth 2 / SSO / JWT', level: 'strong' },
          ],
        },
        {
          title: 'Infrastructure & delivery',
          lead: 'Servers, deployment pipelines, caching and monitoring.',
          items: [
            { name: 'Linux VPS administration', level: 'core' },
            { name: 'OpenLiteSpeed / CyberPanel', level: 'core' },
            { name: 'GitHub Actions CI/CD', level: 'core' },
            { name: 'Cloudflare · DNS, cache rules, WAF, bot control', level: 'core' },
            { name: 'cPanel / DirectAdmin', level: 'strong' },
            { name: 'nginx / Apache / php-fpm', level: 'strong' },
            { name: 'PM2 & Node process management', level: 'strong' },
            { name: 'TLS / ACME, LiteSpeed Cache', level: 'strong' },
            { name: 'Mail · Postfix, Dovecot, Exim, DMARC', level: 'working' },
            { name: 'Docker', level: 'working' },
          ],
        },
        {
          title: 'SEO, performance & analytics',
          lead: 'Making sites fast and easy to find in search.',
          items: [
            { name: 'Technical SEO', level: 'core' },
            { name: 'Core Web Vitals & LCP tuning', level: 'strong' },
            { name: 'Structured data · JSON-LD', level: 'strong' },
            { name: 'i18n & hreflang', level: 'strong' },
            { name: 'Crawl budget & faceted-navigation control', level: 'strong' },
            { name: 'Google Search Console & crawl diagnostics', level: 'strong' },
            { name: 'GA4 · Tag Manager · Looker Studio', level: 'strong' },
            { name: 'Rank Math / Yoast', level: 'strong' },
          ],
        },
        {
          title: 'Engineering practice & AI tooling',
          lead: 'How the code gets written, checked and released.',
          items: [
            { name: 'Git · trunk-based, semantic releases', level: 'core' },
            { name: 'Claude Code & agentic workflows', level: 'core' },
            { name: 'Multilingual products · WPML, Polylang & custom engines', level: 'core' },
            { name: 'Vitest · PHPUnit · test-gated CI', level: 'strong' },
            { name: 'MCP servers & tool integration', level: 'strong' },
            { name: 'Technical writing · specs, runbooks, changelogs', level: 'strong' },
          ],
        },
      ],
    },
    abilities: {
      id: 'abilities',
      title: 'What I can own end to end',
      lead: 'Work I take on and finish on my own.',
      items: [
        { title: 'Figma to production', text: 'I turn a design file into a working Next.js or Vue front end with typed components, accessible markup and a real build pipeline.' },
        { title: 'Custom WordPress builds', text: 'I model the content the way the business works, using custom post types, ACF fields and editor-friendly blocks, and write a theme that stays fast as the site grows.' },
        { title: 'Headless WordPress', text: 'WordPress stays the editing tool and the data source through REST, WPGraphQL and the Store API, while visitors get a fast Next.js front end.' },
        { title: 'Undocumented APIs', text: 'When a bank, ERP or delivery API has partial or outdated documentation, I map its real behaviour by testing endpoints, logging every request and response, and reconciling state by polling.' },
        { title: 'Plugins others depend on', text: 'I release WordPress and WooCommerce plugins with licensing, automatic updates, database migrations, safe activation and a clean uninstall.' },
        { title: 'Store rescue', text: 'I take over a slow, hacked or unfinished WooCommerce site, audit it, remove the damage, update PHP and plugins, and bring the loading speed back to normal.' },
        { title: 'Production diagnostics', text: 'I use access logs, slow query logs and server metrics to find what actually causes a slowdown, instead of restarting services and hoping.' },
        { title: 'Sync engines', text: 'I design one-way and two-way sync between shops and ERP systems, with safe repeated writes, sanity checks on incoming data, a dry-run mode and a pause switch.' },
        { title: 'Multilingual by default', text: 'I build Georgian and English versions from the start, so every URL, template and cache entry is tied to its language.' },
      ],
    },
    workstyle: {
      id: 'work-style',
      title: 'How I work',
      lead: 'How I work on every project.',
      items: [
        { title: 'Check the code before blaming the cache.', text: 'I reproduce every bug and trace it to a specific line before changing anything. A guess is not a diagnosis.' },
        { title: 'Small, verified steps.', text: 'I work in small steps and check the visible result once before moving on. No large rewrites, no untested changes.' },
        { title: 'Read-only until told otherwise.', text: 'I treat live data, client shops and third-party systems as read-only unless the task is specifically to change them.' },
        { title: 'Plan, then build, then review.', text: 'Complex work starts with a written plan that we agree on. It is then built in parts, tested and released through CI.' },
        { title: 'Logs that answer questions.', text: 'Every payment, sync and API call records its full request and response, so a later problem can be traced instead of guessed at.' },
        { title: 'Async and written.', text: 'Clear commit messages, changelogs and short guides, so the next person can continue exactly where I stopped.' },
      ],
    },
    principles: {
      id: 'principles',
      title: 'Principles',
      lead: 'Rules I follow in production work.',
      items: [
        { title: 'Performance is a constraint, not a feature.', text: 'Extra database work on a page that runs on every request is a bug and is fixed like one.' },
        { title: 'Data integrity beats convenience.', text: 'A sync that can delete half the data after one incomplete response must be guarded before anything else is added to it.' },
        { title: 'Production changes go through CI.', text: 'Deploys happen from a pushed commit, never from a hand-copied file. Rollback is a revert.' },
        { title: 'The source of truth is decided in advance.', text: 'One-way syncs stay one-way. When two systems disagree, the design already says which one is right.' },
        { title: 'Every integration is observable.', text: 'Requests, statuses and identifiers are logged, and local records match the provider within one sync cycle.' },
        { title: 'Simple solutions win.', text: 'Standard tools, clear configuration, fewer moving parts. Clever code is harder for the next person to maintain.' },
      ],
    },
    experience: {
      id: 'experience',
      title: 'Experience',
      items: [
        {
          period: '2018 — present',
          role: 'Founder & Lead Developer',
          org: 'Samsiani Web',
          orgHref: 'https://samsiani.com',
          text: 'Independent studio providing web development, technical SEO and hosting for clients in retail, industrial B2B, consumer lending, automotive and education. Work includes WordPress and WooCommerce sites on Divi, Avada, Elementor and WoodMart, custom plugins, and headless Next.js front ends. I am the long-term engineering partner for several of the larger online stores in Georgia, covering payments, ERP sync, speed and infrastructure.',
        },
        {
          period: '2025 — present',
          role: 'Founder, plugin products',
          org: 'CodeOn',
          orgHref: 'https://codeon.ge',
          text: 'A line of WordPress and WooCommerce plugins for the Georgian market: card and installment payments for every major bank, ERP sync, delivery, SMS and a multilingual engine. Each product ships with licensing, automatic updates, documentation and support.',
        },
        {
          period: 'Earlier',
          role: 'Web Developer & Project Manager',
          org: 'E-commerce brands',
          text: 'Built and managed online stores and corporate sites for wine, fashion, furniture and retail brands, covering development, optimisation, technical support and SEO.',
        },
      ],
    },
    education: {
      id: 'languages',
      title: 'Languages',
      langsTitle: 'Languages',
      langs: [
        { name: 'Georgian', level: 'Native' },
        { name: 'English', level: 'Professional working' },
      ],
    },
    contact: {
      id: 'contact',
      title: 'Let’s talk',
      lead: 'Available for remote and contract work. Email is the fastest way to reach me.',
      cta: 'Write to me',
    },
  },
};
